### get 
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### post
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### post
POST http://localhost:3000/coupon HTTP/1.1
content-type: application/json

{
    "libelle": "Chaussette en promo",
    "pourcentage": "50",
    "dateValidite": "30/03/2021"
}

### get
GET http://localhost:3000/coupon HTTP/1.1

### get
GET http://localhost:3000/coupon/603f51e40f03e30fb0453f85 HTTP/1.1

### get
GET http://localhost:3000/ HTTP/1.1